### ISSUE TITLE
Importing error

### ISSUE THREAD

**Issue by Persephone** [stoneharry/Spell-Editor-GUI-V2#19] opened 2015-11-25 07:58 UTC
When I attempt to import a clean dbc 

i get this error:

![image](https://cloud.githubusercontent.com/assets/541084/11391432/b119f270-9352-11e5-94dc-799b16e4bef3.png)

Any ideas what is wrong?

**Comment by stoneharry** [comment] 2015-11-25 19:36
Closing as duplicate of issue https://github.com/stoneharry/Spell-Editor-GUI-V2/issues/14

**Closed** 2015-12-10 21:54 UTC
Labels: duplicate
